version: "3.8"

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - chromadb
      - ollama
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/mydatabase
      CHROMA_DB_URL: http://chromadb:8000
      OLLAMA_API_URL: http://ollama:11434
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb-data:/data
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network

volumes:
  postgres-data:
  chromadb-data:
  ollama-data:

networks:
  app-network: