import type { Metadata } from 'next';

import './globals.css';

import { Inter } from 'next/font/google';

import Navbar from '@/components/navbar';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata: Metadata = {
  title: '명전이 | 명지전문대학 학사도우미',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}